### ISSUE TITLE
Error in NLStart

### ISSUE THREAD

**Issue by Netlogo123** [SESYNC-ci/rnetlogo-lesson#13]
Hi, I am new to RNetlogo and Netlogo. I just downloaded Netlogo 5.3.1 for R. Wrote the below code, however, NLstart is having error. Error says, it could not find NLStart. May I know how to rectify the error.

Here is the code:

#Install needed packages
install.packages("RNetLogo")
library(RNetLogo)
library(dplyr)
library(rJava)

#Set the directory
getwd()
setwd("C:/Users/queen/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/NetLogo 5.3.1")

#This code starts the Netlogo GUI
n1.path<-getwd()
NLStart(n1.path) #Netlogo window should open

**Comment by reblake** [comment]
Hi, this lesson has been deprecated since 2018 and is no longer being updated.  Sorry for the confusion.  We've now added a badge to the README to indicate the deprecated status.
