### ISSUE TITLE
more tests of mac install

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/rnetlogo-lesson#3]
Issue with getting RNetLogo going on a Mac seem to stem from a combination of Xcode version, Java location, and minor NetLogo 5.3.1 restructuring. While I have the lesson working now on OS 10.11, I'm not sure how robust the steps are.

First, the issues:

1. Xcode Version: looks like Xcode 8 when installed on <= OS 10.11 is missing some libraries that r package igraph relies on. I [downgraded](https://developer.apple.com/download/more/) to Xcode 7.3.1. I'm not sure what igraph installation would do if you had never installed Xcode.

1. Java location: perhaps having to do with how I installed Java, the rJava library can't find libjvm.dylib, hence the call to `dyn.load()` below.

1. In NetLogo 5.3.1 on a Mac, that nl.path should be '/Applications/NetLogo 5.3.1/Java' and the model path is '/Applications/NetLogo 5.3.1/model'.

So here's what I had to do for installation, note that I already had Java 8 installed.

1. from terminal `R CMD javareconf`

1. from R, `install.packages("rJava"); install.packages("igraph");install.packages("RNetLogo")`. yes, installing the last one should get the dependencies, but good to break it up to see where problems arise.

1. then get start with the following

```
Sys.setenv(NOAWT=1)
JAVA_HOME <- system('/usr/libexec/java_home', intern=TRUE)
dyn.load(paste0(JAVA_HOME, '/jre/lib/server/libjvm.dylib'))
library(RNetLogo)

nl.path <- '/Users/icarroll/Applications/NetLogo 5.3.1/Java'
NLStart(nl.path, gui=FALSE)
model.path <- file.path("models", "Sample Models", "Biology", "Wolf Sheep Predation.nlogo")
NLLoadModel(file.path(nl.path, "..", model.path))
```

Some/all of this should be tested on another Mac!

**Comment by khondula** [comment]
Seems to have worked for me, with a little tweaking:

1 & 2 as above
3. located `libjvm.dylib` in the NetLogo JRE folder and used that path for `dyn.load()`. (searched for that file and just located the file path). Also needed a `/` at the end of Java ending the `nl.path` for `NLStart()` to work, otherwise I get a "cannot change working directory" error

```
Sys.setenv(NOAWT=1)
dyn.load("/Applications/NetLogo/JRE/Contents/Home/jre/lib/server/libjvm.dylib")
library(RNetLogo)

nl.path <- '/Applications/NetLogo/Java/'
NLStart(nl.path, gui=FALSE)
model.path <- file.path("models", "Sample Models", "Biology", "Wolf Sheep Predation.nlogo")
NLLoadModel(file.path(nl.path, "..", model.path))
NLCommand("setup")
NLReport("count sheep")
```

hooray!

**Comment by itcarroll** [comment]
I think we actually ended up with more windows install issues (mostly 64-bit R users running 32-bit Java) than Mac ones!
